version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bonchDvach-backend
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - skynet

networks:
  skynet:
    external: true